name: Log into Caprover
description: Log into Caprover using OTP
author: Daniil Veremchuk

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  otp-url:
    description: OTP URL, usually in the format of `otpauth//` URL
    required: true
    default: ''
  otp-window:
    description: If under this window (in seconds), wait to generate fresh OTP
    required: false
    default: 5

# Define your outputs here.
outputs:
  otp-token:
    description: 'The OTP Token'

runs:
  main: dist/index.js
  using: node20
